name: Feature Request
description: Suggest a new capability or improvement
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: idea
    attributes:
      label: Feature Description

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves

  - type: textarea
    id: context
    attributes:
      label: Context / Use Case
